name: Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: hirokawa-beach

          template: classic
          config_display: columns
          config_timezone: Asia/Tokyo
          config_order: base.header, languages, isocalendar, habits, base.activity

          base: header, activity

          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_details: percentage
          plugin_languages_threshold: 1%
          plugin_languages_other: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph
